In [121]:
import pandas as pd
import datetime
import numpy as np
from keras.utils import np_utils

In [122]:
dataset = pd.read_csv('dell_dataset.csv')

In [123]:
dataset['Dates'] = [d.split('-')[2] for d in dataset['Date']]
dataset['Months'] = [d.split('-')[1] for d in dataset['Date']]
dataset['Years'] = [d.split('-')[0] for d in dataset['Date']]

In [124]:
dataset = dataset[['S.No', 'Product', 'Place', 'Date', 'Festival_week', 'Dates', 'Months', 'Years', 'Sales']]

In [125]:
dataset = dataset.drop(['Date'], axis=1)
dataset = dataset.drop(['S.No'], axis=1)

In [126]:
dataset.sort_values(by='Years')

,Product,Place,Festival_week,Dates,Months,Years,Sales
0,dell_inspiron_3000,hyderabad,no,01,01,2013,9
26301,dell_xps,hyderabad,no,10,01,2013,14
26300,dell_xps,hyderabad,no,09,01,2013,10
26299,dell_xps,hyderabad,no,08,01,2013,6
26298,dell_xps,hyderabad,no,07,01,2013,5
26297,dell_xps,hyderabad,no,06,01,2013,7
26296,dell_xps,hyderabad,no,05,01,2013,11
26295,dell_xps,hyderabad,no,04,01,2013,5
26294,dell_xps,hyderabad,no,03,01,2013,6
26293,dell_xps,hyderabad,no,02,01,2013,5
15337,dell_vostro,indore,no,01,01,2013,9
15338,dell_vostro,indore,no,02,01,2013,14
15339,dell_vostro,indore,no,03,01,2013,10
15340,dell_vostro,indore,no,04,01,2013,7
15341,dell_vostro,indore,no,05,01,2013,8
15342,dell_vostro,indore,no,06,01,2013,8
15343,dell_vostro,indore,no,07,01,2013,9
15344,dell_vostro,indore,no,08,01,2013,10
15345,dell_vostro,indore,no,09,01,2013,12
15346,dell_vostro,indore,no,10,01,2013,6
15347,dell_vostro,indore,sankranthi,11,01,2013,10
15348,dell_vostro,indore,sankranthi,12,01,2013,13
15349,dell_vostro,indore,sankranthi,13,01,2013,9
15350,dell_vostro,indore,sankranthi,14,01,2013,13
15351,dell_vostro,indore,sankranthi,15,01,2013,13
15352,dell_vostro,indore,sankranthi,16,01,2013,12
26302,dell_xps,hyderabad,sankranthi,11,01,2013,31
26303,dell_xps,hyderabad,sankranthi,12,01,2013,24
26304,dell_xps,hyderabad,sankranthi,13,01,2013,29
26305,dell_xps,hyderabad,sankranthi,14,01,2013,26
...,...,...,...,...,...,...,...
19610,dell_inspiron_5000,hyderabad,ganesh chaturthi,14,09,2018,28
19611,dell_inspiron_5000,hyderabad,ganesh chaturthi,15,09,2018,24
19612,dell_inspiron_5000,hyderabad,ganesh chaturthi,16,09,2018,26
19613,dell_inspiron_5000,hyderabad,no,17,09,2018,18
19614,dell_inspiron_5000,hyderabad,no,18,09,2018,14
19615,dell_inspiron_5000,hyderabad,no,19,09,2018,26
19616,dell_inspiron_5000,hyderabad,no,20,09,2018,15
19617,dell_inspiron_5000,hyderabad,no,21,09,2018,23
19618,dell_inspiron_5000,hyderabad,no,22,09,2018,13
19603,dell_inspiron_5000,hyderabad,no,07,09,2018,21
19694,dell_inspiron_5000,hyderabad,no,07,12,2018,28
19602,dell_inspiron_5000,hyderabad,no,06,09,2018,11
19600,dell_inspiron_5000,hyderabad,no,04,09,2018,24
19585,dell_inspiron_5000,hyderabad,no,20,08,2018,20
19586,dell_inspiron_5000,hyderabad,no,21,08,2018,22
19587,dell_inspiron_5000,hyderabad,no,22,08,2018,20
19588,dell_inspiron_5000,hyderabad,no,23,08,2018,18
19589,dell_inspiron_5000,hyderabad,no,24,08,2018,22
19590,dell_inspiron_5000,hyderabad,no,25,08,2018,23
19591,dell_inspiron_5000,hyderabad,no,26,08,2018,22
19592,dell_inspiron_5000,hyderabad,no,27,08,2018,11
19593,dell_inspiron_5000,hyderabad,no,28,08,2018,17
19594,dell_inspiron_5000,hyderabad,no,29,08,2018,14
19595,dell_inspiron_5000,hyderabad,no,30,08,2018,15
19596,dell_inspiron_5000,hyderabad,no,31,08,2018,17
19597,dell_inspiron_5000,hyderabad,no,01,09,2018,19
19598,dell_inspiron_5000,hyderabad,no,02,09,2018,26
19599,dell_inspiron_5000,hyderabad,no,03,09,2018,18
19601,dell_inspiron_5000,hyderabad,no,05,09,2018,21
35055,dell_xps,indore,no,31,12,2018,4

In [127]:
data = dataset.values

In [128]:
print(data[:,6])

[9 3 12 ... 6 8 4]

In [129]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
data[:, 0] = labelencoder_X_1.fit_transform(data[:, 0])

data[:, 1] = labelencoder_X_1.fit_transform(data[:, 1])

data[:, 2] = labelencoder_X_1.fit_transform(data[:, 2])

In [130]:
print(len(data[:,6]))

35056

In [131]:
onehotencoder = OneHotEncoder(categorical_features = [0,1,2])
data = onehotencoder.fit_transform(data).toarray()
print(len(data[0,:]))

17

In [132]:
X_train = data[:29216,:]
X_test = data[29216:,:]

In [133]:
print(X_train.shape)

(29216, 17)

In [134]:
Y_train = X_train[:,16]
X_train = X_train[:,:16]

In [135]:
Y_test = X_test[:,16]
X_test = X_test[:,:16]

In [136]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
print(Y_train[40])

(29216, 16)
(5840, 16)
(29216,)
(5840,)
9.0

In [137]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [138]:
classifier = Sequential()

In [139]:
classifier.add(Dense(output_dim = 50, init = 'uniform', activation = 'relu', input_dim = 16))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=16, units=50, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [140]:
classifier.add(Dense(output_dim = 30, init = 'uniform', activation = 'relu'))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=30, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [141]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'relu'))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [142]:
classifier.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [143]:
classifier.fit(X_train, Y_train, batch_size = 10, nb_epoch = 10)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.

Epoch 1/50
29216/29216 [==============================] - 3s 120us/step - loss: 228.9728
Epoch 2/50
29216/29216 [==============================] - 3s 113us/step - loss: 228.9728
Epoch 3/50
29216/29216 [==============================] - 3s 93us/step - loss: 228.9728
Epoch 4/50
29216/29216 [==============================] - ETA: 0s - loss: 228.842 - 3s 93us/step - loss: 228.9728
Epoch 5/50
29216/29216 [==============================] - 3s 93us/step - loss: 228.9728
Epoch 6/50
29216/29216 [==============================] - 3s 97us/step - loss: 228.9728
Epoch 7/50
29216/29216 [==============================] - 3s 100us/step - loss: 228.9728
Epoch 8/50
 1910/29216 [>.............................] - ETA: 2s - loss: 228.1508

KeyboardInterrupt:

In [81]:
y_pred = classifier.predict(X_test)

In [82]:
len(y_pred)

5840

In [83]:
mse = (np.square(y_pred - Y_test)).mean(axis=None)

In [84]:
print(mse)

136.3135383886538

In [85]:
print(y_pred)

[[13.078014 ]
 [13.573995 ]
 [13.2774105]
 ...
 [20.185255 ]
 [20.298912 ]
 [20.419407 ]]

In [86]:
print(Y_test)

[20. 27. 17. ...  6.  8.  4.]

In [87]:
print(Y_test[:50])

[20. 27. 17. 17. 20. 19. 15. 23. 26. 22. 24. 26. 24. 22. 26. 14. 23. 20.
 17. 16. 20. 23. 24. 20. 17. 14. 25. 23. 24. 23. 16. 24. 22. 19. 20. 21.
 23. 17. 16. 15. 28. 20. 22. 16. 15. 20. 17. 21. 18. 22.]

In [88]:
print(y_pred[:50])

[[13.078014 ]
 [13.573995 ]
 [13.2774105]
 [13.387999 ]
 [13.30603  ]
 [13.417175 ]
 [13.423696 ]
 [13.25608  ]
 [19.124645 ]
 [19.38249  ]
 [19.618809 ]
 [19.221268 ]
 [19.279873 ]
 [19.240799 ]
 [19.214981 ]
 [13.241148 ]
 [13.256432 ]
 [13.26923  ]
 [13.057278 ]
 [13.108183 ]
 [13.338189 ]
 [13.2658415]
 [13.176463 ]
 [13.45039  ]
 [13.010422 ]
 [13.1339445]
 [13.2476   ]
 [13.368098 ]
 [13.184494 ]
 [13.341714 ]
 [13.340921 ]
 [13.078869 ]
 [13.574846 ]
 [13.278265 ]
 [13.388853 ]
 [13.306885 ]
 [13.418032 ]
 [13.42455  ]
 [13.256935 ]
 [12.98244  ]
 [13.273508 ]
 [13.535923 ]
 [13.2422695]
 [13.155383 ]
 [13.1509905]
 [13.456029 ]
 [13.242002 ]
 [13.257286 ]
 [13.270083 ]
 [13.058131 ]]

In [97]:
X_test[1]

array([0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 2.015e+03])